services:
  - type: web
    name: isabel-sistema
    env: node
    plan: free
    buildCommand: npm install --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0